version: '3.8'

services:
  php-web:
    image: php:8.2-apache
    ports:
      - "8080:80"
    volumes:
      - ./php/public:/var/www/html
      - ./php/scripts-php:/var/www/scripts
    networks:
      - php-network
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: aula_db
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - php-network
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"
    environment:
      PMA_HOST: mysql
    depends_on:
      - mysql

volumes:
  mysql-data: {}  # Proper volume declaration

networks:
  php-network:
